name: conan2
author: dandielo@iceshard.net
description: Initialization and configuration of Conan2 package manager.

inputs:
  conan-cache:
    description: 'Allows the action to setup caching for Conan2 packages.'
    required: false
    default: false
  conan-cache-version:
    description: 'User provided version string for the cache key. Allows to cut-off all previous cache keys.'
    required: false
    default: 'v1'
  conan-config-url:
    description: 'User provided URL containing valid conan2 configuration files. (ex.: a github repository)'
    required: false
    default: 'https://github.com/iceshard-engine/conan-config.git'
  # Conan2 profile settings
  conan-profile:
    description: 'The profile to be used for this action.'
    required: false
    default: 'default'
  conan-modify-profile:
    description: 'If enabled, sets selected values in the default profile.'
    required: false
    default: false
  conan-profile-compiler:
    description: 'The compiler to be used in the default conan profile.'
    required: false
  conan-profile-compiler-version:
    description: 'The compiler version to be used in the default conan profile.'
    required: false
  conan-profile-cppstd:
    description: 'The C++ standard version to be used in the default conan profile.'
    required: false
    default: '20'
  conan-profile-libcxx:
    description: 'The C++ standard library to be used in the default conan profile. (linux-only)'
    required: false
    default: 'libc++'

outputs:
  conan-profile-compiler:
    description: 'Compiler of the selected profile.'
    value: ${{ steps.conan-profile-reader.outputs.compiler-name }}
  conan-profile-compiler-version:
    description: 'Compiler version of the selected profile.'
    value: ${{ steps.conan-profile-reader.outputs.compiler-version }}

runs:
  using: 'composite'
  steps:
    - name: Conan2 - Install required packages
      shell: pwsh
      run: |
        pip install conan

    - name: Conan2 - Install crudini (ubuntu-only)
      if: ${{ runner.os == 'Linux' }}
      shell: pwsh
      run: |
        sudo apt install crudini

    - name: Conan2 - Configure for IceShard engine
      shell: pwsh
      run: conan config install ${{ inputs.conan-config-url }}

    # Preparing the default profile
    - name: Conan2 - Detect current machine default profile
      if: ${{ inputs.conan-profile == 'default' }}
      shell: pwsh
      run: |
        conan profile detect

    - name: Conan2 - Store profile path
      shell: pwsh
      run: |
        echo "CONAN_PROFILE_PATH=$(conan profile path ${{ inputs.conan-profile }})" >> "$env:GITHUB_ENV"

    - name: Conan2 - Set 'compiler' for default profile (${{ inputs.conan-profile-compiler }}-${{ inputs.conan-profile-compiler-version }})
      if: ${{ inputs.conan-modify-profile == 'true' && inputs.conan-profile-compiler != '' && inputs.conan-profile-compiler-version != '' }}
      shell: pwsh
      run: |
        python $env:GITHUB_ACTION_PATH/ini_write.py $env:CONAN_PROFILE_PATH settings compiler ${{ inputs.conan-profile-compiler }}
        python $env:GITHUB_ACTION_PATH/ini_write.py $env:CONAN_PROFILE_PATH settings compiler.version ${{ inputs.conan-profile-compiler-version }}
    - name: Conan2 - Set 'compiler.cppstd' for default profile (c++${{ inputs.conan-profile-cppstd }})
      if: ${{ inputs.conan-modify-profile == 'true' && inputs.conan-profile-cppstd != '' }}
      shell: pwsh
      run: |
        python $env:GITHUB_ACTION_PATH/ini_write.py $env:CONAN_PROFILE_PATH settings compiler.cppstd ${{ inputs.conan-profile-cppstd }}
    - name: Conan2 - Set 'compiler.libcxx' for default profile (${{ inputs.conan-profile-libcxx }})
      if: ${{ inputs.conan-modify-profile == 'true' && inputs.conan-profile-libcxx != '' && inputs.conan-profile-compiler == 'clang' }}
      shell: pwsh
      run: |
        python $env:GITHUB_ACTION_PATH/ini_write.py $env:CONAN_PROFILE_PATH settings compiler.libcxx ${{ inputs.conan-profile-libcxx }}

    # Setting up the caching mechanism
    - name: Conan2 - Setup cache
      if: ${{ inputs.conan-cache == 'true' }}
      uses: actions/cache@v4
      env:
        cache-name: conan2-packages
      with:
        path: ~/.conan2
        key: ${{ env.cache-name }}-${{ runner.os }}-${{ inputs.conan-cache-version }}-${{ hashFiles('**/conanfile.txt', '**/conanprofiles.txt') }}
        restore-keys: |
          ${{ env.cache-name }}-${{ runner.os }}-${{ inputs.conan-cache-version }}

    # Output the selected conan-profile information
    - name: Conan2 - Output profile info
      id: conan-profile-reader
      shell: pwsh
      run: |
        echo "::notice::Reading compiler information from '$env:CONAN_PROFILE_PATH' conan profile."
        echo "::notice::$(python $env:GITHUB_ACTION_PATH/ini_read.py $env:CONAN_PROFILE_PATH settings compiler)"
        echo "compiler-name=$(python $env:GITHUB_ACTION_PATH/ini_read.py $env:CONAN_PROFILE_PATH settings compiler)" >> $GITHUB_OUTPUT
        echo "compiler-version=$(python $env:GITHUB_ACTION_PATH/ini_read.py $env:CONAN_PROFILE_PATH settings compiler.version)" >> $GITHUB_OUTPUT

    # Fixing up Conan2 settings if given clang version does not exist yet
    - name: Conan2 - Ensure Conan2 knows clang version
      if: ${{ steps.conan-profile-reader.compiler-name == 'clang' }}
      shell: pwsh
      run: |
        python $env:GITHUB_ACTION_PATH/conan2_clang_version_support_fix.py ${{ steps.conan-profile-reader.compiler-version }}
