name: Deploy

on:
  push:
    branches:
    - main
    tags:
    - v*
    
env:
  conan_package_id: # You conan package ID
  conan_upstream_remote: 'conan-iceshard' # Organization default remote.
  conan_config_url: 'https://github.com/iceshard-engine/conan-config.git' # Organization default config repo.
  
  

jobs:
  deploy-windows-debug:
    name: Deploy (Windows-Debug)
    uses: iceshard-engine/gh-actions/.github/workflows/rw_conan_deploy_package.yaml@main
    with:
      host: windows-latest
      conan_package: ${{ env.conan_package_id }}
      conan_upstream_remote: ${{ env.conan_upstream_remote }}
      conan_config_url: ${{ env.conan_config_url }}
      conan_options: '-s"build_type=Debug"'
      conan_upload_options: '--all'
    secrets:
      conan_user: 'iceshard'
      conan_password: ${{ secrets.CONAN_PASSWORD }}

  deploy-windows-release:
    name: Deploy (Windows-Release)
    uses: iceshard-engine/gh-actions/.github/workflows/rw_conan_deploy_package.yaml@main
    with:
      host: windows-latest
      conan_package: ${{ env.conan_package_id }}
      conan_upstream_remote: ${{ env.conan_upstream_remote }}
      conan_config_url: ${{ env.conan_config_url }}
      conan_options: '-s"build_type=Release"'
      conan_upload_options: '--all'
    secrets:
      conan_user: 'iceshard'
      conan_password: ${{ secrets.CONAN_PASSWORD }}

  deploy-linux-debug:
    name: Deploy (Linux-Debug)
    uses: iceshard-engine/gh-actions/.github/workflows/rw_conan_deploy_package.yaml@main
    with:
      host: ubuntu-latest
      conan_package: ${{ env.conan_package_id }}
      conan_upstream_remote: ${{ env.conan_upstream_remote }}
      conan_config_url: ${{ env.conan_config_url }}
      conan_options: '-s"build_type=Debug"'
      conan_profile: 'gcc-11.0-linux-x86_64'
      conan_upload_options: '--all'
    secrets:
      conan_user: 'iceshard'
      conan_password: ${{ secrets.CONAN_PASSWORD }}

  deploy-linux-release:
    name: Deploy (Linux-Release)
    uses: iceshard-engine/gh-actions/.github/workflows/rw_conan_deploy_package.yaml@main
    with:
      host: ubuntu-latest
      conan_package: ${{ env.conan_package_id }}
      conan_upstream_remote: ${{ env.conan_upstream_remote }}
      conan_config_url: ${{ env.conan_config_url }}
      conan_options: '-s"build_type=Release"'
      conan_profile: 'gcc-11.0-linux-x86_64'
      conan_upload_options: '--all'
    secrets:
      conan_user: 'iceshard'
      conan_password: ${{ secrets.CONAN_PASSWORD }}
