name: IceShard Conan Validation

on:
  push:
    branches: [ $default-branch ]

jobs:
  validate-windows:
    name: Validate (Windows)
    uses: iceshard-engine/.github/workflows/rw_conan_create_package.yaml@main
    with:
      host: windows-latest
      conan_package: # You conan package ID 
      conan_config_url: 'https://github.com/iceshard-engine/conan-config.git' # Organizations default configs.
      conan_options: '-s"build_type=Debug"'

  validate-linux:
    name: Validate (Linux)
    uses: iceshard-engine/.github/workflows/rw_conan_create_package.yaml@main
    with:
      host: ubuntu-latest
      conan_package: # You conan package ID
      conan_config_url: 'https://github.com/iceshard-engine/conan-config.git' # Organization default configs.
      conan_options: '-s"build_type=Debug"'
      conan_profile: 'gcc-11.0-linux-x86_64' # Organizations default conan profile. (used as default in the 'engine' project)
